name: practice_book
description: "実践flutterの書籍を演習"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: any
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.13
  go_router: ^16.0.0
  image: ^4.5.4
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  flutter_gen_runner: ^5.11.0

flutter:
  generate: true
  assets:
  - assets/

  uses-material-design: true

flutter_gen:
  integrations:
    flutter_svg: true